name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install docker-compose make gcc openjdk-11-jdk git openssl -y
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
          curl -L https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz --output apache-maven-3.6.3-bin.tar.gz
          tar xvfz apache-maven-3.6.3-bin.tar.gz
          sudo mv apache-maven-3.6.3 /usr/local/
          export PATH=$PATH:/usr/local/apache-maven-3.6.3/bin
          
      - name: Create the configuration directory
        run: |
          mkdir workdir
          sed -i 's|PERSISTENT_VOLUME_DIRECTORY=/opt/charon|PERSISTENT_VOLUME_DIRECTORY='$(pwd)'/workdir|g' environment.conf

      - name: Build and start the environment
        run: |
          make destroy
          make all
          docker-compose build
          docker-compose up -d
